imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Assetic Configuration
assetic:
    debug: '%kernel.debug%'
    use_controller: false
    bundles: []
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: '%kernel.root_dir%/Resources/java/compiler.jar'
        #yui_css:
        #    jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Default configuration for extension with alias: "enqueue"
enqueue:
    transport:            # Required
        default: "rabbitmq_amqp"
#            alias:                ~
#            dsn:                  ~
        rabbitmq_amqp:

#            # The connection to AMQP broker set as a string. Other parameters are ignored if set
#            dsn:                  ~

            # The host to connect too. Note: Max 1024 characters
            host:                 message_bus

#            # Port on the host.
#            port:                 5672
#
#            # The user name to use. Note: Max 128 characters.
#            user:                 guest
#
#            # Password. Note: Max 128 characters.
#            pass:                 guest
#
#            # The virtual host on the host. Note: Max 128 characters.
#            vhost:                /
#
#            # Connection timeout. Note: 0 or greater seconds. May be fractional.
#            connect_timeout:      0
#
#            # Timeout in for income activity. Note: 0 or greater seconds. May be fractional.
#            read_timeout:         0
#
#            # Timeout in for outcome activity. Note: 0 or greater seconds. May be fractional.
#            write_timeout:        0
#            persisted:            false
#            lazy:                 true

            # The option tells whether RabbitMQ broker has delay plugin installed or not
            delay_plugin_installed: false
    client: ~